print("\n        Bem Vindo ao Sudoko\n")
print("---------------------------------------")
print("[5] [3] [ ] - [ ] [7] [ ] - [ ] [ ] [ ]")
print("[6] [ ] [ ] - [1] [9] [5] - [ ] [ ] [ ]")
print("[ ] [9] [8] - [ ] [ ] [ ] - [ ] [6] [ ]")
print("---------------------------------------")
print("[8] [ ] [ ] - [ ] [6] [ ] - [ ] [ ] [3]")
print("[4] [ ] [ ] - [8] [ ] [3] - [ ] [ ] [1]")
print("[7] [ ] [ ] - [ ] [3] [ ] - [ ] [ ] [6]")
print("---------------------------------------")
print("[ ] [6] [ ] - [ ] [ ] [ ] - [2] [8] [ ]")
print("[ ] [ ] [ ] - [4] [1] [9] - [ ] [ ] [5]")
print("[ ] [ ] [ ] - [ ] [8] [ ] - [ ] [7] [9]")
print("---------------------------------------")
print("Esse é o seu jogo \n")
fileira1 = input("Digite a Primeira fileira: \n")
fileira2 = input("Digite a Segunda fileira: \n")
fileira3 = input("Digite a Terceira fileira: \n")
